package hostel.management.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class StudentFeeDetails extends javax.swing.JFrame {

    /**
     * 
      /*insert into messcount values("200750","2022-06-8",,"","");
update messcount set year1=YEAR(date),month=MONTH(date) where admission_number='200750';
select * from messcount;
*/
     /* Creates new form StudentFeeDetails
     */
     ResultSet rs1,rsa,rs4;
    Connection conn=DBConnection.getConnection();
    String query1="select sum(daily_count)from messcount where admission_number=? and month=? and year1=?";
    String query2="UPDATE feedetails set skipped_meals=? where admission_number=? and year1=? and month1=? ";
     String query4="UPDATE feedetails set fees=6100-(attendance*150)-(skipped_meals/3)*130 where admission_number=? and year1=? and month1=? ";
//    String query3 = "SELECT * from feedetails where admission_number=? and year1=? and month1=?";
    String query5="UPDATE feedetails set status='Paid' where admission_number=? and year1=? and month1=? ";
    
    String Mint,Y;
    int absentdays;
    int msumcount;
    String admno=login.Adm.admno;
  
    public StudentFeeDetails() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        Year = new javax.swing.JComboBox<>();
        Month = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ML = new javax.swing.JLabel();
        YL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        presentdays = new javax.swing.JLabel();
        mc = new javax.swing.JLabel();
        tf = new javax.swing.JLabel();
        status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 71, 97));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FEE DETAILS");

        jButton9.setBackground(new java.awt.Color(0, 71, 97));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closeicon.png"))); // NOI18N
        jButton9.setToolTipText("");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 71, 97));
        jButton10.setText("CHECK");
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        Year.setBackground(new java.awt.Color(0, 71, 97));
        Year.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Year.setForeground(new java.awt.Color(255, 255, 255));
        Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023" }));
        Year.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Year", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        Month.setBackground(new java.awt.Color(0, 71, 97));
        Month.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Month.setForeground(new java.awt.Color(255, 255, 255));
        Month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "December", "November", "October", "September", "August", "July", "June", "May", "April", "March", "February", "January" }));
        Month.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Month", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Month, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Year, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton9)
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton10)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 700));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Absent Days  :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 100, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Skipped Food Count  :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Total Fees  :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Status  :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 71, 97));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Pay Now");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        ML.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ML.setForeground(new java.awt.Color(0, 71, 97));
        ML.setText("MONTH");
        getContentPane().add(ML, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        YL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        YL.setForeground(new java.awt.Color(0, 71, 97));
        YL.setText("YEAR");
        getContentPane().add(YL, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 71, 97));
        jLabel3.setText("--");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        presentdays.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(presentdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 100, -1));

        mc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(mc, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 120, -1));

        tf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    int indexi;
    private void YearActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
//        indexi = Year.getSelectedIndex();
//        YearPanel.setSelectedIndex(indexi);
        
    }  
/**/
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        student_home sh = new student_home();
                sh.show();
                
                dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

/*
    private void YearActionPerformed(java.awt.event.ActionEvent evt) {                                     

        
    }                                    
*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
             PreparedStatement pst=conn.prepareStatement(query5);
             pst.setString(1,admno);
             pst.setString(2,Y);
             pst.setString(3, Mint);
             pst.executeUpdate();
         } catch (SQLException ex) {
             Logger.getLogger(StudentFeeDetails.class.getName()).log(Level.SEVERE, null, ex);
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
Y=Year.getSelectedItem().toString();
        String M=Month.getSelectedItem().toString();
        YL.setText(Y);
        ML.setText(M);

        System.out.println(Y+M);
        
        if("2022".equals(Y) || "2023".equals(Y))
        {
            switch (M) {
                case "December" -> 
                {
                    Mint="12";
                }
                case "November" -> 
                {
                    Mint="11";
                }
                case "October" -> 
                {
                    Mint="10";
                }
                case "September" -> 
                {
                    Mint="9";
                }
                case "August" -> 
                {
                   Mint="8"; 
                }
                case "July" -> 
                {
                   Mint="7"; 
                }
                case "June" -> 
                {
                    Mint="6";
                }
                case "January" -> 
                {
                    Mint="1";
                }
                case "February" -> 
                {
                    Mint="2";
                }
                default -> throw new AssertionError();
            }
            
//          presentdays.setText(rs.getString());  
        }
         try {
             
             PreparedStatement pst=conn.prepareStatement("INSERT INTO Feedetails VALUES (?,?,?,?,?,?,?)");
             pst.setString(1,admno);
             pst.setString(2,Y);
             pst.setString(3,Mint);
             pst.setInt(4,0);
             pst.setInt(5,0);
             pst.setInt(6,0);
             pst.setString(7,"not paid");
             
             pst.executeUpdate();   
         } catch (SQLException ex) {
//             Logger.getLogger(StudentFeeDetails.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
        try {
             PreparedStatement pst1=conn.prepareStatement(query1);
             pst1.setString(1, admno);
             pst1.setString(2, Mint);
             pst1.setString(3, Y);
             rs1=pst1.executeQuery();
             rs1.next();
             msumcount=rs1.getInt(1);
             System.out.println(msumcount);
         } catch (SQLException ex) {
             Logger.getLogger(StudentFeeDetails.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        try {
             PreparedStatement psta=conn.prepareStatement("select sum(absent_days)from registers WHERE out_month=? AND out_year=? AND admission_number=?");
             psta.setString(3, admno);
             psta.setString(1, Mint);
             psta.setString(2, Y);
             rsa=psta.executeQuery();
             rsa.next();
             
            absentdays=rsa.getInt(1);
            System.out.println(absentdays);
             
         } catch (SQLException ex) {
              System.out.println("ohhhnooo123");
             Logger.getLogger(StudentFeeDetails.class.getName()).log(Level.SEVERE, null, ex);
         }
         try {
             PreparedStatement pstb=conn.prepareStatement("UPDATE Feedetails SET attendance=?,month1=? WHERE admission_number=? ");
             pstb.setInt(1,absentdays);
             pstb.setString(2,Mint);
             pstb.setString(3,admno);
             
             pstb.executeUpdate();
         } catch (SQLException ex) {
             Logger.getLogger(StudentFeeDetails.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        try {
             PreparedStatement pst2=conn.prepareStatement(query2);
             pst2.setInt(1,msumcount);
             pst2.setString(2,admno);
             pst2.setString(3,Y);
             pst2.setString(4, Mint);
             pst2.executeUpdate();
         } catch (SQLException ex) {
             Logger.getLogger(StudentFeeDetails.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        try {
             PreparedStatement pst3=conn.prepareStatement(query4);
             pst3.setString(1,admno);
             pst3.setString(2,Y);
             pst3.setString(3, Mint);
             pst3.executeUpdate();
         } catch (SQLException ex) {
             Logger.getLogger(StudentFeeDetails.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
        


//        setCount();
//        setCount2();
//        setFee();
//        showd();
try {

             PreparedStatement pst=conn.prepareStatement("SELECT * FROM feedetails WHERE admission_number=? AND month1=? AND year1=?");
             System.out.println(admno+Mint+Y);
             
             pst.setString(1, admno);
             pst.setString(2, Mint);
             pst.setString(3, Y);
             rs4=pst.executeQuery();
//             System.out.println("111"+rs4);
             
             rs4.next();
//             System.out.println("oho"+rs4.next());
             
                 

             presentdays.setText(rs4.getString(4));
             mc.setText(rs4.getString(6));
             tf.setText(rs4.getString(5));
             status.setText(rs4.getString(7));
             System.out.println(rs4.getString(1)+rs4.getString(2)+rs4.getString(3)+rs4.getString(4));
  // Result set is empty

             
                 
             
             
         } catch (SQLException ex) {
             Logger.getLogger(StudentFeeDetails.class.getName()).log(Level.SEVERE, null, ex);
         }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentFeeDetails().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ML;
    private javax.swing.JComboBox<String> Month;
    private javax.swing.JLabel YL;
    private javax.swing.JComboBox<String> Year;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mc;
    private javax.swing.JLabel presentdays;
    private javax.swing.JLabel status;
    private javax.swing.JLabel tf;
    // End of variables declaration//GEN-END:variables
}

  
//    trigerCREATE DEFINER=`root`@`localhost` TRIGGER `feedetails_AFTER_INSERT` AFTER INSERT ON `feedetails` FOR EACH ROW BEGIN
//  DECLARE v_fees INT;
//
//   CALL CalculateFees(NEW.admission_number, NEW.year1, NEW.month1, v_fees);
//
//   UPDATE FeeDetails
//   SET fees = v_fees
//   WHERE admission_number = NEW.admission_number AND year1 = NEW.year1 AND month1 = NEW.month1;
//END
    
//    CREATE DEFINER=`root`@`localhost` PROCEDURE `CalculateFees`(IN p_admission_number INT, IN p_year INT, IN p_month INT, OUT p_fees INT)
//BEGIN
//DECLARE v_skipped_meals INT;
//   DECLARE v_attended_days INT;
//
//   SELECT SUM(daily_count) INTO v_skipped_meals
//FROM MessCount
//WHERE admission_number = p_admission_number AND year = p_year AND month = p_month;
//
//   SELECT attendance INTO v_attended_days
//   FROM FeeDetails as f
//   WHERE f.admission_number = p_admission_number AND  f.year1= p_year AND f.month1 = p_month;
//
//   SET p_fees = 200 * v_attended_days - (v_skipped_meals / 3) * 130;
//END
//